<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSaja9o3\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSaja9o3/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSaja9o3.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSaja9o3\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSaja9o3\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Saja9o3',
    'container.build_id' => 'e9af76ad',
    'container.build_time' => 1543931019,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSaja9o3');
